<?xml version="1.0"?>

<!-- XML definition file for Lustre-es6_0 -->
<!-- Copyright (c) 2014, DataDirect Networks, Inc. -->
<!-- Authors: Li Xi <lixi at ddn.com> -->
<!-- This file is automatically generated, do NOT edit this file directly -->

<!DOCTYPE definition [
	<!ELEMENT definition     (version,math_entry*,entry+)>
	<!ELEMENT version        (#PCDATA)>

	<!ELEMENT math_entry     (left_operand,operation,right_operand,tsdb_name,type_instance)>
	<!ELEMENT left_operand   (#PCDATA)>
	<!ELEMENT operation      (#PCDATA)>
	<!ELEMENT right_operand  (#PCDATA)>
	<!ELEMENT tsdb_name      (#PCDATA)>
	<!ELEMENT type_instance  (#PCDATA)>

	<!ELEMENT entry          (subpath,mode,write_after_read?,item*,entry*)>
	<!ELEMENT mode           (#PCDATA)>
	<!ELEMENT write_after_read (#PCDATA)>

	<!ELEMENT subpath        (subpath_type,path,subpath_field*)>
	<!ELEMENT subpath_type   (#PCDATA)>
	<!ELEMENT path           (#PCDATA)>

	<!ELEMENT subpath_field  (index,name)>
	<!ELEMENT index          (#PCDATA)>
	<!ELEMENT name           (#PCDATA)>

	<!ELEMENT item           (name,context?,pattern,field+)>
	<!ELEMENT pattern        (#PCDATA)>
	<!ELEMENT context        (#PCDATA|start_string|end_string)*>

	<!ELEMENT start_string   (#PCDATA)> 
	<!ELEMENT end_string     (#PCDATA)>

	<!ELEMENT field          (index,name,type,first_value?,option+)>
	<!ELEMENT type           (#PCDATA)>
	<!ELEMENT first_value	 (#PCDATA)>

	<!ELEMENT option         (name,string)>
	<!ELEMENT string         (#PCDATA)>
]>

<definition>
	<version>es6_0</version>
	<math_entry>
		<left_operand>client_stats_read_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_read_samples</right_operand>
		<tsdb_name>client_stats_read_mean</tsdb_name>
		<type_instance>read_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_write_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_write_samples</right_operand>
		<tsdb_name>client_stats_write_mean</tsdb_name>
		<type_instance>write_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_open_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_open_samples</right_operand>
		<tsdb_name>client_stats_open_mean</tsdb_name>
		<type_instance>open_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_close_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_close_samples</right_operand>
		<tsdb_name>client_stats_close_mean</tsdb_name>
		<type_instance>close_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_mmap_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_mmap_samples</right_operand>
		<tsdb_name>client_stats_mmap_mean</tsdb_name>
		<type_instance>mmap_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_page_fault_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_page_fault_samples</right_operand>
		<tsdb_name>client_stats_page_fault_mean</tsdb_name>
		<type_instance>page_fault_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_page_mkwrite_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_page_mkwrite_samples</right_operand>
		<tsdb_name>client_stats_page_mkwrite_mean</tsdb_name>
		<type_instance>page_mkwrite_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_seek_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_seek_samples</right_operand>
		<tsdb_name>client_stats_seek_mean</tsdb_name>
		<type_instance>seek_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_fsync_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_fsync_samples</right_operand>
		<tsdb_name>client_stats_fsync_mean</tsdb_name>
		<type_instance>fsync_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_readdir_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_readdir_samples</right_operand>
		<tsdb_name>client_stats_readdir_mean</tsdb_name>
		<type_instance>readdir_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_setattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_setattr_samples</right_operand>
		<tsdb_name>client_stats_setattr_mean</tsdb_name>
		<type_instance>setattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_truncate_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_truncate_samples</right_operand>
		<tsdb_name>client_stats_truncate_mean</tsdb_name>
		<type_instance>truncate_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_flock_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_flock_samples</right_operand>
		<tsdb_name>client_stats_flock_mean</tsdb_name>
		<type_instance>flock_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_getattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_getattr_samples</right_operand>
		<tsdb_name>client_stats_getattr_mean</tsdb_name>
		<type_instance>getattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_fallocate_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_fallocate_samples</right_operand>
		<tsdb_name>client_stats_fallocate_mean</tsdb_name>
		<type_instance>fallocate_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_create_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_create_samples</right_operand>
		<tsdb_name>client_stats_create_mean</tsdb_name>
		<type_instance>create_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_link_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_link_samples</right_operand>
		<tsdb_name>client_stats_link_mean</tsdb_name>
		<type_instance>link_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_unlink_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_unlink_samples</right_operand>
		<tsdb_name>client_stats_unlink_mean</tsdb_name>
		<type_instance>unlink_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_symlink_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_symlink_samples</right_operand>
		<tsdb_name>client_stats_symlink_mean</tsdb_name>
		<type_instance>symlink_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_mkdir_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_mkdir_samples</right_operand>
		<tsdb_name>client_stats_mkdir_mean</tsdb_name>
		<type_instance>mkdir_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_rmdir_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_rmdir_samples</right_operand>
		<tsdb_name>client_stats_rmdir_mean</tsdb_name>
		<type_instance>rmdir_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_mknod_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_mknod_samples</right_operand>
		<tsdb_name>client_stats_mknod_mean</tsdb_name>
		<type_instance>mknod_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_rename_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_rename_samples</right_operand>
		<tsdb_name>client_stats_rename_mean</tsdb_name>
		<type_instance>rename_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_statfs_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_statfs_samples</right_operand>
		<tsdb_name>client_stats_statfs_mean</tsdb_name>
		<type_instance>statfs_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_setxattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_setxattr_samples</right_operand>
		<tsdb_name>client_stats_setxattr_mean</tsdb_name>
		<type_instance>setxattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_getxattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_getxattr_samples</right_operand>
		<tsdb_name>client_stats_getxattr_mean</tsdb_name>
		<type_instance>getxattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_listxattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_listxattr_samples</right_operand>
		<tsdb_name>client_stats_listxattr_mean</tsdb_name>
		<type_instance>listxattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_removexattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_removexattr_samples</right_operand>
		<tsdb_name>client_stats_removexattr_mean</tsdb_name>
		<type_instance>removexattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>client_stats_inode_permission_sum</left_operand>
		<operation>/</operation>
		<right_operand>client_stats_inode_permission_samples</right_operand>
		<tsdb_name>client_stats_inode_permission_mean</tsdb_name>
		<type_instance>inode_permission_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_filesinfo_total</left_operand>
		<operation>-</operation>
		<right_operand>mdt_filesinfo_free</right_operand>
		<tsdb_name>mdt_filesinfo_used</tsdb_name>
		<type_instance>filesused</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_kbytesinfo_total</left_operand>
		<operation>-</operation>
		<right_operand>mdt_kbytesinfo_free</right_operand>
		<tsdb_name>mdt_kbytesinfo_used</tsdb_name>
		<type_instance>kbytesused</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>ost_filesinfo_total</left_operand>
		<operation>-</operation>
		<right_operand>ost_filesinfo_free</right_operand>
		<tsdb_name>ost_filesinfo_used</tsdb_name>
		<type_instance>filesused</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>ost_kbytesinfo_total</left_operand>
		<operation>-</operation>
		<right_operand>ost_kbytesinfo_free</right_operand>
		<tsdb_name>ost_kbytesinfo_used</tsdb_name>
		<type_instance>kbytesused</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_waittime_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_stats_req_waittime_mean</tsdb_name>
		<type_instance>req_waittime_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_waittime_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_stats_req_waittime_mean_square</tsdb_name>
		<type_instance>req_waittime_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_qdepth_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_stats_req_qdepth_mean</tsdb_name>
		<type_instance>req_qdepth_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_qdepth_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_stats_req_qdepth_mean_square</tsdb_name>
		<type_instance>req_qdepth_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_active_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_stats_req_active_mean</tsdb_name>
		<type_instance>req_active_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_active_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_stats_req_active_mean_square</tsdb_name>
		<type_instance>req_active_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_timeout_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_stats_req_timeout_mean</tsdb_name>
		<type_instance>req_timeout_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_req_timeout_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_stats_req_timeout_mean_square</tsdb_name>
		<type_instance>req_timeout_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_reqbuf_avail_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_stats_reqbuf_avail_mean</tsdb_name>
		<type_instance>reqbuf_avail_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_reqbuf_avail_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_stats_reqbuf_avail_mean_square</tsdb_name>
		<type_instance>reqbuf_avail_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_ldlm_ibits_enqueue_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_ldlm_ibits_enqueue_samples</right_operand>
		<tsdb_name>mdt_stats_ldlm_ibits_enqueue_mean</tsdb_name>
		<type_instance>ldlm_ibits_enqueue_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_ldlm_ibits_enqueue_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_ldlm_ibits_enqueue_samples</right_operand>
		<tsdb_name>mdt_stats_ldlm_ibits_enqueue_mean_square</tsdb_name>
		<type_instance>ldlm_ibits_enqueue_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_getattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_getattr_samples</right_operand>
		<tsdb_name>mdt_stats_mds_getattr_mean</tsdb_name>
		<type_instance>mds_getattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_getattr_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_getattr_samples</right_operand>
		<tsdb_name>mdt_stats_mds_getattr_mean_square</tsdb_name>
		<type_instance>mds_getattr_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_connect_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_connect_samples</right_operand>
		<tsdb_name>mdt_stats_mds_connect_mean</tsdb_name>
		<type_instance>mds_connect_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_connect_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_connect_samples</right_operand>
		<tsdb_name>mdt_stats_mds_connect_mean_square</tsdb_name>
		<type_instance>mds_connect_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_get_root_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_get_root_samples</right_operand>
		<tsdb_name>mdt_stats_mds_get_root_mean</tsdb_name>
		<type_instance>mds_get_root_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_get_root_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_get_root_samples</right_operand>
		<tsdb_name>mdt_stats_mds_get_root_mean_square</tsdb_name>
		<type_instance>mds_get_root_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_statfs_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_statfs_samples</right_operand>
		<tsdb_name>mdt_stats_mds_statfs_mean</tsdb_name>
		<type_instance>mds_statfs_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_statfs_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_statfs_samples</right_operand>
		<tsdb_name>mdt_stats_mds_statfs_mean_square</tsdb_name>
		<type_instance>mds_statfs_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_getxattr_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_getxattr_samples</right_operand>
		<tsdb_name>mdt_stats_mds_getxattr_mean</tsdb_name>
		<type_instance>mds_getxattr_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_mds_getxattr_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_mds_getxattr_samples</right_operand>
		<tsdb_name>mdt_stats_mds_getxattr_mean_square</tsdb_name>
		<type_instance>mds_getxattr_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_obd_ping_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_obd_ping_samples</right_operand>
		<tsdb_name>mdt_stats_obd_ping_mean</tsdb_name>
		<type_instance>obd_ping_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_stats_obd_ping_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_stats_obd_ping_samples</right_operand>
		<tsdb_name>mdt_stats_obd_ping_mean_square</tsdb_name>
		<type_instance>obd_ping_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_waittime_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_waittime_mean</tsdb_name>
		<type_instance>req_waittime_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_waittime_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_waittime_mean_square</tsdb_name>
		<type_instance>req_waittime_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_qdepth_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_qdepth_mean</tsdb_name>
		<type_instance>req_qdepth_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_qdepth_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_qdepth_mean_square</tsdb_name>
		<type_instance>req_qdepth_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_active_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_active_mean</tsdb_name>
		<type_instance>req_active_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_active_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_active_mean_square</tsdb_name>
		<type_instance>req_active_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_timeout_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_timeout_mean</tsdb_name>
		<type_instance>req_timeout_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_req_timeout_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_req_timeout_mean_square</tsdb_name>
		<type_instance>req_timeout_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_reqbuf_avail_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_reqbuf_avail_mean</tsdb_name>
		<type_instance>reqbuf_avail_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_reqbuf_avail_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_reqbuf_avail_mean_square</tsdb_name>
		<type_instance>reqbuf_avail_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_mds_close_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_mds_close_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_mds_close_mean</tsdb_name>
		<type_instance>mds_close_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_mds_close_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_mds_close_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_mds_close_mean_square</tsdb_name>
		<type_instance>mds_close_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_mds_readpage_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_mds_readpage_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_mds_readpage_mean</tsdb_name>
		<type_instance>mds_readpage_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_readpage_stats_mds_readpage_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_readpage_stats_mds_readpage_samples</right_operand>
		<tsdb_name>mdt_readpage_stats_mds_readpage_mean_square</tsdb_name>
		<type_instance>mds_readpage_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_waittime_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_waittime_mean</tsdb_name>
		<type_instance>req_waittime_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_waittime_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_waittime_mean_square</tsdb_name>
		<type_instance>req_waittime_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_qdepth_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_qdepth_mean</tsdb_name>
		<type_instance>req_qdepth_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_qdepth_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_qdepth_mean_square</tsdb_name>
		<type_instance>req_qdepth_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_active_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_active_mean</tsdb_name>
		<type_instance>req_active_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_active_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_active_mean_square</tsdb_name>
		<type_instance>req_active_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_timeout_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_timeout_mean</tsdb_name>
		<type_instance>req_timeout_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_req_timeout_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_req_timeout_mean_square</tsdb_name>
		<type_instance>req_timeout_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_reqbuf_avail_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_reqbuf_avail_mean</tsdb_name>
		<type_instance>reqbuf_avail_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_setattr_stats_reqbuf_avail_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_setattr_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_setattr_stats_reqbuf_avail_mean_square</tsdb_name>
		<type_instance>reqbuf_avail_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_waittime_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_waittime_mean</tsdb_name>
		<type_instance>req_waittime_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_waittime_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_waittime_mean_square</tsdb_name>
		<type_instance>req_waittime_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_qdepth_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_qdepth_mean</tsdb_name>
		<type_instance>req_qdepth_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_qdepth_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_qdepth_mean_square</tsdb_name>
		<type_instance>req_qdepth_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_active_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_active_mean</tsdb_name>
		<type_instance>req_active_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_active_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_active_mean_square</tsdb_name>
		<type_instance>req_active_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_timeout_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_timeout_mean</tsdb_name>
		<type_instance>req_timeout_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_req_timeout_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_fld_stats_req_timeout_mean_square</tsdb_name>
		<type_instance>req_timeout_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_reqbuf_avail_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_fld_stats_reqbuf_avail_mean</tsdb_name>
		<type_instance>reqbuf_avail_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_fld_stats_reqbuf_avail_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_fld_stats_reqbuf_avail_samples</right_operand>
		<tsdb_name>mdt_fld_stats_reqbuf_avail_mean_square</tsdb_name>
		<type_instance>reqbuf_avail_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_waittime_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_waittime_mean</tsdb_name>
		<type_instance>req_waittime_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_waittime_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_waittime_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_waittime_mean_square</tsdb_name>
		<type_instance>req_waittime_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_qdepth_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_qdepth_mean</tsdb_name>
		<type_instance>req_qdepth_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_qdepth_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_qdepth_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_qdepth_mean_square</tsdb_name>
		<type_instance>req_qdepth_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_active_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_active_mean</tsdb_name>
		<type_instance>req_active_mean</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_active_sum_square</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_active_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_active_mean_square</tsdb_name>
		<type_instance>req_active_mean_square</type_instance>
	</math_entry>
	<math_entry>
		<left_operand>mdt_out_stats_req_timeout_sum</left_operand>
		<operation>/</operation>
		<right_operand>mdt_out_stats_req_timeout_samples</right_operand>
		<tsdb_name>mdt_out_stats_req_timeout_mean</tsdb_name>
		<type_instance>req_timeout_mean</type_instance>
	</math_entry>
	<math_entry>