<?xml version="1.0"?>
<!DOCTYPE definition [
	<!ELEMENT definition     (version,entry+)>
	<!ELEMENT version        (#PCDATA)>

	<!ELEMENT entry          (subpath,mode,item*,entry*)>
	<!ELEMENT mode           (#PCDATA)>

	<!ELEMENT subpath        (subpath_type,path,subpath_field*)>
	<!ELEMENT subpath_type   (#PCDATA)>
	<!ELEMENT path           (#PCDATA)>

	<!ELEMENT subpath_field  (index,name)>
	<!ELEMENT index          (#PCDATA)>
	<!ELEMENT name           (#PCDATA)>

	<!ELEMENT item           (name,pattern,field+)>
	<!ELEMENT pattern        (#PCDATA)>

	<!ELEMENT field          (index,name,type,option+)>
	<!ELEMENT type           (#PCDATA)>

	<!ELEMENT option         (name,string)>
	<!ELEMENT string         (#PCDATA)>
]>
<definition>
	<version>2.5.51</version>
	<entry>
		<subpath>
			<subpath_type>constant</subpath_type>
			<path>/proc/fs/lustre</path>
		</subpath>
		<mode>directory</mode>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>health_check</path>
			</subpath>
			<mode>file</mode>
			<item>
				<name>health</name>
				<pattern>(.+)</pattern>
				<field>
					<index>1</index>
					<name>health</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
		</entry>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>version</path>
			</subpath>
			<mode>file</mode>
			<item>
				<name>lustre_version</name>
				<pattern>lustre: ([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)</pattern>
				<field>
					<index>1</index>
					<name>version</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
			<item>
				<name>kernel_type</name>
				<pattern>kernel: (patchless_client)</pattern>
				<field>
					<index>1</index>
					<name>kernel_type</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
			<item>
				<name>build_version</name>
				<pattern>build:  (.+)</pattern>
				<field>
					<index>1</index>
					<name>build_version</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
		</entry>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>mdt</path>
			</subpath>
			<mode>directory</mode>
			<entry>
				<subpath>
					<subpath_type>regular_expression</subpath_type>
					<path>(^.+-MDT[0-9a-fA-F]+$)</path>
					<subpath_field>
						<index>1</index>
						<name>mdt_name</name>
					</subpath_field>
				</subpath>
				<mode>directory</mode>
				<entry>
					<subpath>
						<subpath_type>constant</subpath_type>
						<path>md_stats</path>
					</subpath>
					<mode>file</mode>
					<item>
						<name>md_stats_open</name>
						<pattern>open +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>open</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>open</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_close</name>
						<pattern>close +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>close</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>close</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_mknod</name>
						<pattern>mknod +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>mknod</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>mknod</string>
							</option>
						</field>
					</item>
					<item>
						<name>link</name>
						<pattern>link +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>link</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>link</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_unlink</name>
						<pattern>unlink +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>unlink</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>unlink</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_mkdir</name>
						<pattern>mkdir +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>mkdir</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>mkdir</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_rmdir</name>
						<pattern>rmdir +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>rmdir</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>rmdir</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_rename</name>
						<pattern>rename +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>rename</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_getattr</name>
						<pattern>getattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>getattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_setattr</name>
						<pattern>setattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>setattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_getxattr</name>
						<pattern>getxattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>getxattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getxattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_setxattr</name>
						<pattern>setxattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>setxattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setxattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_statfs</name>
						<pattern>statfs +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>statfs</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>statfs</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_sync</name>
						<pattern>sync +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>sync</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>sync</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_samedir_rename</name>
						<pattern>samedir_rename +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>samedir_rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>samedir_rename</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_crossdir_rename</name>
						<pattern>crossdir_rename +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>crossdir_rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>crossdir_rename</string>
							</option>
						</field>
					</item>
				</entry>
				<entry>
					<subpath>
						<subpath_type>constant</subpath_type>
						<path>job_stats</path>
					</subpath>
					<mode>file</mode>
					<item>
						<name>mdt_jobstats</name>
						<pattern>- +job_id: +(.+)
 +snapshot_time: +.+
  open: +\{ samples: +([[:digit:]]+).+
  close: +\{ samples: +([[:digit:]]+).+
  mknod: +\{ samples: +([[:digit:]]+).+
  link: +\{ samples: +([[:digit:]]+).+
  unlink: +\{ samples: +([[:digit:]]+).+
  mkdir: +\{ samples: +([[:digit:]]+).+
  rmdir: +\{ samples: +([[:digit:]]+).+
  rename: +\{ samples: +([[:digit:]]+).+
  getattr: +\{ samples: +([[:digit:]]+).+
  setattr: +\{ samples: +([[:digit:]]+).+
  getxattr: +\{ samples: +([[:digit:]]+).+
  setxattr: +\{ samples: +([[:digit:]]+).+
  statfs: +\{ samples: +([[:digit:]]+).+
  sync: +\{ samples: +([[:digit:]]+).+
  samedir_rename: +\{ samples: +([[:digit:]]+).+
  crossdir_rename: +\{ samples: +([[:digit:]]+).+</pattern>
	  					<field>
							<index>1</index>
							<name>job_id</name>
							<type>string</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>job_id</string>
							</option>
						</field>
	  					<field>
							<index>2</index>
							<name>open</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>open</string>
							</option>
						</field>
						<field>
							<index>3</index>
							<name>close</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>close</string>
							</option>
						</field>
	  					<field>
							<index>4</index>
							<name>mknod</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>mknod</string>
							</option>
						</field>
						<field>
							<index>5</index>
							<name>link</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>link</string>
							</option>
						</field>
						<field>
							<index>6</index>
							<name>unlink</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>unlink</string>
							</option>
						</field>
						<field>
							<index>7</index>
							<name>mkdir</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>mkdir</string>
							</option>
						</field>
						<field>
							<index>8</index>
							<name>rmdir</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>rmdir</string>
							</option>
						</field>
						<field>
							<index>9</index>
							<name>rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>rename</string>
							</option>
						</field>
						<field>
							<index>10</index>
							<name>getattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getattr</string>
							</option>
						</field>
						<field>
							<index>11</index>
							<name>setattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setattr</string>
							</option>
						</field>
						<field>
							<index>12</index>
							<name>getxattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getxattr</string>
							</option>
						</field>
						<field>
							<index>13</index>
							<name>setxattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setxattr</string>
							</option>
						</field>
						<field>
							<index>14</index>
							<name>statfs</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>statfs</string>
							</option>
						</field>
						<field>
							<index>15</index>
							<name>sync</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>sync</string>
							</option>
						</field>
						<field>
							<index>16</index>
							<name>samedir_rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>samedir_rename</string>
							</option>
						</field>
						<field>
							<index>17</index>
							<name>crossdir_rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>jobstat</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string>${content:job_id}</string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>crossdir_rename</string>
							</option>
						</field>
					</item>
				</entry>
			</entry>
		</entry>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>obdfilter</path>
			</subpath>
			<mode>directory</mode>
			<entry>
				<subpath>
					<subpath_type>regular_expression</subpath_type>
					<path>(^.+-OST[0-9a-fA-F]+$)</path>
					<subpath_field>
						<index>1</index>
						<name>ost_name</name>
					</subpath_field>
				</subpath>
				<mode>directory</mode>
				<entry>
					<subpath>
						<subpath_type>constant</subpath_type>
						<path>stats</path>
					</subpath>
					<mode>file</mode>
					<item>
						<name>oost_stats_read</name>
						<pattern>read_bytes +([[:digit:]]+) samples \[bytes\] [[:digit:]]+ [[:digit:]]+ ([[:digit:]]+)</pattern>
						<field>
							<index>1</index>
							<name>read_samples</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>read_samples</string>
							</option>
						</field>
						<field>
							<index>2</index>
							<name>read_bytes</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>read_bytes</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_write</name>
						<pattern>write_bytes +([[:digit:]]+) samples \[bytes\] [[:digit:]]+ [[:digit:]]+ ([[:digit:]]+)</pattern>
						<field>
							<index>1</index>
							<name>write_samples</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>write_samples</string>
							</option>
						</field>
						<field>
							<index>2</index>
							<name>write_bytes</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>